### ISSUE TITLE
Each Problem: ECONNREFUSED

### ISSUE THREAD

**Issue by Latrasis** [bulkan/async-you#22]
Pushka-3:async-school latrasis$ async-you verify each.js
    Verifying "EACH"...

    ACTUAL:   ""
    EXPECTED: "{ [Error: connect ECONNREFUSED]"

    ACTUAL:   null
    EXPECTED: "  errno: 'ECONNREFUSED',"

    ACTUAL:   null
    EXPECTED: "  syscall: 'connect' }"

    ACTUAL:   null
    EXPECTED: ""

    # FAIL

    Your solution to EACH didn't match the expected output.
    Try again!

**Comment by manonthemat** [comment]
Also, notice that you should actually use console.log and not console.error in the result callback. I used console.error at first, too. It makes more sense to me to use console.error when printing out errors, but the exercise actually wants you to use console.log instead.

**Comment by Latrasis** [comment]
Thanks!

**Comment by kyrios** [comment]
I'm having the same problem. The issue is closed. What is the solution?


    node -v
    v0.12.7


    15:31 $ async-you run each.js 
    events.js:85
      throw er; // Unhandled 'error' event
            ^
    Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

**Comment by jedateach** [comment]
I have the same problem. @kyrios - did you find a solution?

**Comment by MohammedEssehemy** [comment]
the same issue here, how to solve it.
