### ISSUE TITLE
Exercise 3 of 7, async.each, why do we have 'return done();'?

### ISSUE THREAD

**Issue by RichardBansal** [bulkan/async-you#26]
For line 13 below where it states 'return done()', why are we using this instead of 'done()'. I assume they are equivalent. Propose to change to just done().

    var http = require('http')
      , async = require('async');
    async.each(['cat', 'meerkat', 'penguin'], function(item, done){
      var opts = {
        hostname: 'http://httpbin.org',
        path: '/post',
        method: 'POST'
      };
      var req = http.request(opts, function(res){
        res.on('data', function(chunk){
        });
        res.on('end', function(){
         return done();
        });
      });
      req.write(item);
      req.end();
    },
    function(err){
      if (err) console.log(err);
    });

**Comment by bulkan** [comment]
They are equivalent but it's best practice to return callback calls.
