### ISSUE TITLE
Having trouble with npm "async" dependency

### ISSUE THREAD

**Issue by qayshp** [bulkan/async-you#27]
Using a clean install of npm and async-you, I get this error when trying to run even the solution code.
```
$ async-you run test.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/action/workspace/test.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I was able to resolve this by doing a local `npm install async`, but a global install does not fix this.
Maybe this is only relevant to my install of node/npm, but I'd like to know why.

Screen shot:
![screen shot 2015-04-07 at 7 09 34 pm](https://cloud.githubusercontent.com/assets/714080/7037822/bd067c80-dd5d-11e4-9e61-3ce2e775ec66.png)

**Comment by bulkan** [comment]
Which version of node and npm are you using  ?

**Comment by qayshp** [comment]
`node -v: v0.10.26`
`npm -v: 1.4.3`

**Comment by qayshp** [comment]
For reference, from the same path that I got the error (before installing `async` locally):
```
$ npm list async-you -g
/home/action/.parts/lib
└── async-you@1.0.0 
```
```
$ npm list async -g
/home/action/.parts/lib
├── async@0.9.0 
├─┬ async-you@1.0.0
│ └── async@0.9.0 
└─┬ npm@1.4.3
  └─┬ request@2.30.0
    └─┬ form-data@0.1.2
      └── async@0.2.9 
```

**Comment by qayshp** [comment]
Also, I checked versions and it doesn't matter if I do `npm install async@0.9.0` or latest, as long as it isn't global.

I'm really thinking it's the install of node and npm on [Nitrous (with ref link)](https://www.nitrous.io/join/Xte_542jztE), but still can't tell why.

**Comment by bulkan** [comment]
I was able to replicate this on my machine by doing;

```shell
mkdir temp; cd temp;
npm install async-you
./node_modules/.bin/async-you run solution-workshopper.js
```

I believe the way `workshopper-exercise` is running the solution file has changed

**Comment by alph486** [comment]
some other exercises that depend on some other dependency usually make that part of their readme; to `npm install` the dependency when in the workshop directory. This way its a bit more user friendly. I made small changes in #34 to be more clear.

Thanks for the workshop btw, @bulkan!

**Comment by bulkan** [comment]
#34 fixes this
