### ISSUE TITLE
Series challenge

### ISSUE THREAD

**Issue by mintyPT** [bulkan/async-you#29]
This is my code. I'm doing this in coffeescript.

	http  = require 'http'
	async = require 'async'
	fs    = require 'fs'

	f1 = (cb) ->
		cb null, process.argv[2]

	f2 = (file, cb) ->
		# console.log file
		fs.readFile file, 'utf8', (err, data) ->
			if err
				cb err

			cb null, data

	f3 = (link, cb) ->
		# console.log link
		body = ''

		req = http.get link, (res) ->

			res.on 'data', (chunk)->
				body += chunk.toString()

			res.on 'end', ()->
				cb null, body

		req.on 'error', (err) ->
			cb err

	last = (error, result) ->
		console.log result

	async.waterfall [f1, f2, f3], last

Trying to get *http://localhost:3131/one* I get thee following:

{ [Error: socket hang up] code: 'ECONNRESET' }

Any ideas?

**Comment by mintyPT** [comment]
Quick note: I later got the same issue on other challenges

**Comment by bulkan** [comment]
Can you provide the transpiled version of your code please?

**Comment by mintyPT** [comment]
Sure. here goes:


	
	// Generated by CoffeeScript 1.9.1
	var async, f1, f2, f3, fs, http, last;
	
	http = require('http');
	
	async = require('async');
	
	fs = require('fs');
	
	f1 = function(cb) {
		return cb(null, process.argv[2]);
	};
	
	f2 = function(file, cb) {
		return fs.readFile(file, 'utf8', function(err, data) {
			if (err) {
				cb(err);
			}
			return cb(null, data);
		});
	};
	
	f3 = function(link, cb) {
		var body, req;
		body = '';
		req = http.get(link, function(res) {
			res.on('data', function(chunk) {
				return body += chunk.toString();
			});
			return res.on('end', function() {
				return cb(null, body);
			});
		});
		return req.on('error', function(err) {
			return cb(err);
		});
	};
	
	last = function(error, result) {
		return console.log(result);
	};
	
	async.waterfall([f1, f2, f3], last);

**Comment by bulkan** [comment]
Sorry for really late reply I believe you're not running this properly. Your solution is using `async.waterfall` and the title of this issue mentions `Series challenge` ...

Running the transpiled code against the waterfall exercise passes.
