### ISSUE TITLE
naming the error function in waterfall challenge

### ISSUE THREAD

**Issue by sindhus** [bulkan/async-you#30]
hi!

I am new to asynchronous javascript programming and I had to watch [this](https://www.youtube.com/watch?v=tNKXN8ZCXpw) video a couple of times to figure out how the waterfall method works.

I was unable to understand where this `done(null, data)` existed in the [solution for waterfall challenge](https://github.com/bulkan/async-you/blob/master/exercises/waterfall/solution/solution.js). It then occurred to me that "done()" is the function that is given along with the array of functions to async.waterfall. Had it been named in the solution I wouldn't have to look so hard.

Thanks.

```
async.waterfall([
	function(done){
		fs.readFile(process.argv[2], function(err, data){
			if (err) return done(err);
			done(null, data);
		});
	},

	function(data, done) {
		var body = '';
		http.get(data.toString().trimRight(), function(res){
			res.on('data', function(chunk){
				body += chunk.toString();
			});

			res.on('end', function(chunk){
				done(null, body);
			});
		}).on('error', function(e){
			done(e);
		});
	}
], function done(err, result){
	if (err) return console.error(err);
	console.log(result);
});
```

**Comment by bulkan** [comment]
I'm not sure I'm understanding your concern. You have correctly identified that `done` is the callback function being passed to a task function in the array of functions that is passed into `async.waterfall`.

**Comment by sindhus** [comment]
I meant to say that without the callback being named "done" its hard to identify visually which function is being called. As a newcomer I am looking for function names than signatures.

**Comment by bulkan** [comment]
I'm more than happy to accept a PR

**Comment by sindhus** [comment]
I sent a PR #33 where I changed all exercises' callback to be named (except whilst because it doesn't work see #32). Thank you :)
