### ISSUE TITLE
async.times and async.reduce explanation

### ISSUE THREAD

**Issue by sindhus** [bulkan/async-you#31]
Is there a reason why async.times and async.reduce challenges have no explanation and asks user to read up this one on their own? While doing these challenges it works out quickly if i can read a small explanation and then proceed to solving the challenge than having to look up the docs. This is trivial in some ways to experienced users but then experienced ones wouldn't be solving these tutorials :)

**Comment by bulkan** [comment]
Hi @sindhus ,

This was the way I wrote these two exercises. If you think there needs to be more explanation then you're more than welcome in submitting a PR.
