### ISSUE TITLE
HTTP a little distracting

### ISSUE THREAD

**Issue by alph486** [bulkan/async-you#35]
I know these are very simple examples, and do not misunderstand me by thinking I am saying they are too "difficult" or anything. But I think having the http posts and (to a lesser extent) gets distracts a bit from the exercises on async. If you miss anything, don't use those much, or even are just having an off day, you can spend a lot of time debugging http instead of dealing with the async stuff. Maybe setTimeouts or some other simple mechanism are better? Even if the expected code for the http parts were given in the instructions, it would remove a lot of extra work to get the concepts of async.

Thanks for the workshop!

**Comment by bulkan** [comment]
Hi @alph486,

Thanks for the feedback but sorry I didn't get back to you sooner just been busy and kind of burnt out.

I kind of agree with you that the HTTP might be too distracting but this workshop has been out and live for a while and I don't believe its a good idea to change it. 

Perhaps we could add more exercises that first use simple examples (i.e setInterval & setTimeout).

**Comment by dcsan** [comment]
I came here to say a similar thing. In fact retrieving the body with pure http get and no middleware is not that trivial... 

http://stackoverflow.com/questions/6968448/where-is-body-in-a-nodejs-http-get-response

also fs.readFileSync() ...

**Comment by bulkan** [comment]
@dcsan as I wrote before this workshop has been out and live for a while and I don't believe its a good idea to change it.
