### ISSUE TITLE
New exercises

### ISSUE THREAD

**Issue by riyadhalnur** [bulkan/async-you#38]
I was thinking of introducing new exercises to the module like `apply` and `auto` among other things. What do you think? I will open the respective PRs if given the go.

**Comment by bulkan** [comment]
Hi @riyadhalnur please do add these exercises. PR's are always welcome

**Comment by riyadhalnur** [comment]
awesome. will open PRs once they're ready :+1:

**Comment by bulkan** [comment]
Thanks in advance.
