### ISSUE TITLE
exercise times - superfluous function?

### ISSUE THREAD

**Issue by Fransz** [bulkan/async-you#42]
In the times exercise, while we post 5 users i'm confused by the way we call our_adduser function.

```
post: function(done){
    async.times(5, function(n, next){
        _addUser(++n, function(err){
            next(err);
        });
    });
}
```

what does wrapping the call to `next` in a new function add? 
`_addUser(++n, next)` seems to work also,  it passes the verify tests.

**Comment by bulkan** [comment]
Thanks for the feedback.
