### ISSUE TITLE
Please start this in a tty-compatible terminal program.

### ISSUE THREAD

**Issue by scott-plutovr** [bulkan/async-you#44]
When I run async-you in either the git-bash MINGW64 terminal or in a Cygwin terminal I receive the message, "Please start this in a tty-compatible terminal program." and nothing else. Is Windows supported?

**Comment by scott-plutovr** [comment]
![image](https://cloud.githubusercontent.com/assets/14023072/15547524/033ed102-2259-11e6-8a68-210e3504c3e3.png)

But I can run async-you help and get output.

**Comment by bulkan** [comment]
Hi @scott-plutovr !

The support for windows and mingw64/cygwin comes from [workshopper](https://github.com/workshopper/workshopper). If workshopper doesnt support than async-you doesn't either.
