### ISSUE TITLE
ECONNREFUSED 127.0.0.1:4242 in EACH exercise

### ISSUE THREAD

**Issue by GeoffreyEmerson** [bulkan/async-you#46]
My code was functionally equivalent to the official solution, but I ended up copy/pasting the official solution in an effort to debug the error. It didn't help.

```
var http = require('http')
  , async = require('async');

async.each(process.argv.slice(2), function(item, done){
  http.get(item, function(res){
    res.on('data', function(chunk){
    });

    res.on('end', function(){
      done(null);
    });
  }).on('error', function(err){
    done(err);
  });
},
function(err){
  if(err) console.error(err);
});
```

```
$ async-you run program.js
{ Error: connect ECONNREFUSED 127.0.0.1:4242
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4242 }
```
Node version:
```
$ node -v
v7.9.0
```

Note that the first url (http://localhost:9345) succeeded silently as expected. It was the second url that failed with the error above.

**Comment by bulkan** [comment]
@GeoffreyEmerson @MohammedEssehemy If i remember correctly this is expected behaviour.  If you look at the setup code for the exercise only one HTTP server is started.

https://github.com/bulkan/async-you/blob/master/exercises/each/exercise.js#L26

**Comment by GeoffreyEmerson** [comment]
@bulkan If it was expected behaviour, shouldn't  it pass the test?

**Comment by bulkan** [comment]
@GeoffreyEmerson the test does pass for me when I run `async_you verify each_solution.js` with the official solution.

![image](https://user-images.githubusercontent.com/13985/27564427-ec52e09a-5b1a-11e7-805a-e3d4f36705f5.png)
