### ISSUE TITLE
Not super clear that there will be an error in the `each` exercise 

### ISSUE THREAD

**Issue by meeple142** [bulkan/async-you#49]
Looking at the solution it now makes sense that one url is good and one is bad. This is a good teaching point to make sure students know how to handle errors. But it would be good to be a little more explicit that one URL will be good and one will be bad. So they make sure to handle it. 
I first thought that you forgot to start a server at `:4242` and was going to make a pull request with the fix. But then ran your solution and understand now. 😄 

Thanks for the great course!

**Comment by bulkan** [comment]
@meeple142 great points. Perhaps we can re-word the exercise ?

**Comment by matthewwyndham** [comment]
I recommend the instructions where the challenge is described be changed to say "Then using http.get, create two GET requests, one to each URL, and console.**_error_** any errors."

I used console.log(err) and kept failing the verify. Then I switched to console.error(err) _(after searching online for why I didn't pass this challenge)_ and I passed without any other changes.

**Comment by bulkan** [comment]
@matthewwyndham please feel free to suggest better wording to the questions.
