### ISSUE TITLE
Async Series Exercise

### ISSUE THREAD

**Issue by davidlares** [bulkan/async-you#50]
Hello. I recently started this workshop and I think this exercise has a bug on a process object Params. 

The explanation of the problem states that we will receiving two parameters. Debugging a little I realize that the process.argv[3] is undefined, and the process.argv[2] is a fle route, so is neccesary the Node FS module to read that File Route and get the URL to process the HTTP requests. 

This is the code that I've been working on, when I run it there's not syntax errors, but when I verify it return empty, I don't know what else to do

```
var http = require('http');
var async = require('async');
var fs = require('fs');

async.series({

	requestOne: function(done){

		fs.readFile(process.argv[2], function(err,furl) {
			if(err) console.log(err);
			http.get(furl.toString(), function(res){
				res.on('data',function(err,data){
					if(err) return err;
					done(null,data.toString());
				})
			})
		})
		
	},
	requestTwo: function(done){

		fs.readFile(process.argv[3], function(err,surl) {
			if(err) console.log(err);

		 	http.get(surl.toString(), function(res){
				res.on('data',function(err,data){
					if(err) return err;
					done(null,data.toString());
				})
			})
		})
	}

}, function(err,results) {
	if(err) return err;
	console.log(results);
});

```

Thanks in advance, any help will be appreciated.

**Comment by impressi-web** [comment]
Here is the question **"Write a program that will receive two URLs as the first and second command-line arguments.
Using http.get, create a GET request to these URLs and pass the response body to the callback.
Pass in an object of task functions, using the property names **requestOne** and **requestTwo**, to **async.series**.  
console.log the results in the callback for series when all the task functions have completed."**

You do not need the **fs** module to complete the task and also you must have only one **console.log** which should be in the callback for series when all the task functions have completed.

Here is my preferred solution:

```
const { get } = require("http");
const { pipeline } = require("stream");
const concat = require("concat-stream");
const async = require("async");

async.series(
  {
    requestOne: function (cb) {
      fetchUrl(process.argv[2], cb);
    },
    requestTwo: function (cb) {
      fetchUrl(process.argv[3], cb);
    },
  },
  (err, results) => {
    if (err) return console.error(err);
    console.log(results);
  }
);

function fetchUrl(url, callback) {
  get(url, (res) => {
    res.setEncoding("utf-8");
    pipeline(
      res,
      concat((data) => {
        callback(null, data);
      }),
      (err) => {
        if (err) return callback(err);
      }
    );
  });
}
```
