### ISSUE TITLE
Impossible to verify whilst exercise

### ISSUE THREAD

**Issue by skinth** [bulkan/async-you#51]
Hi all,
when I try to run (or verify) the whilst exercise the get request doesn't get any results.

This is my code
```
var http = require('http'),
    async = require('async'),
    url = process.argv[2]

var count = 0,
    s = ''

async.whilst(
    () => {
        return s !== 'meerkat'
    },
    (next) => {
        http.get(url, (res) => {
            console.log(res)
            count++
            var body = ''
            res.on('data', (chunk) => {
                body += chunk.toString()
            })
            res.on('end', () => {
                s = body.trim()
                next()
            })
        }).on('error', (err) => console.log(err))
    },
    (err) => {
        if(err) console.log(err)
        console.log(count)
    }
)
```

I try to verify the exercise with the official solution but it doesn't work anyway.
I appreciate anyone help.

Thank you

**Comment by impressi-web** [comment]
first remove `console.log(res)` in your iteratee. change your test function to `( cb ) => cb( null, s !== 'meerkat' )`.

here is my preferred solution:

`const { get } = require("http");
const async = require("async");
const { pipeline } = require("stream");
const concat = require("concat-stream");

let body = "";
let count = 0;

async.whilst(
  function test(cb) {
    cb(null, !body.includes("meerkat"));
  },
  function iter(done) {
    get(process.argv[2], (res) => {
      res.setEncoding("utf-8");
      count ++;
      pipeline(
        res,
        concat((data) => {
          body = data;
          done(null, data);
        }),
        (err) => {
          if (err) return done(err);
        }
      );
    }).on("error", done);
  },
  function (err) {
    if (err) return console.error(err);
    console.log(count);
  }
);
`
